name: Deploy Merlin Index

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.run/**'
      - 'LICENSE'
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  gradle-build:
    name: Gradle Build
    runs-on: ubuntu-latest
    env:
      DEPENDENCY_GRAPH_EXCLUDE_PROJECTS: ':(gradm|initialization|project)'
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Omico Maven Repository
        uses: actions/checkout@v4
        with:
          repository: Omico/maven.omico.me
          ref: repo
          path: maven.omico.me

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          dependency-graph: generate-and-upload

      - env:
          MAVEN_OMICO_LOCAL_URI: 'file://${{ github.workspace }}/maven.omico.me'
        run: ./gradlew deployIndexes --no-daemon --stacktrace

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./build/merlin

  gradle-submit-dependency-graph:
    name: Gradle Submit Dependency Graph
    uses: OmicoDev/gradle-project-initializer-template/.github/workflows/gradle-submit-dependency-graph.yml@main
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: gradle-build
    permissions:
      contents: write

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: gradle-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
