name: Deploy Merlin Index

on:
  push:
    branches:
      - main
    paths:
      - 'merlin/**'
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :merlin-google:run

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/merlin

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
