name: Deploy Merlin Index

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.run/**'
      - 'LICENSE'
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  gradle-build:
    name: Gradle Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Omico Maven Repository
        uses: actions/checkout@v4
        with:
          repository: Omico/maven.omico.me
          ref: repo
          path: maven.omico.me

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - env:
          MAVEN_OMICO_LOCAL_URI: 'file://${{ github.workspace }}/maven.omico.me'
        run: ./gradlew deployIndexes --no-daemon --stacktrace

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/merlin

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: gradle-build
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
